default: &default
  adapter: postgresql
  encoding: unicode
  database: myapp
  username: myuser  
  password: passwd
  port: 57364
  host: database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

staging:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_staging

production:
  <<: *default