apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: back-container
        image: abelyankov/back:v1
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            port: 3000
            path: /
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            port: 3000
            path: /health
          initialDelaySeconds: 60
          periodSeconds: 5
        