apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-example-deployment
  labels:
    app: docker-example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-example-app
  template:
    metadata:
      labels:
        app: docker-example-app
    spec:
      containers:
      - name: docker-example-container
        image: abelyankov/docker-example:v1
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 80
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
        