apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: docker-example
build:
  artifacts:
  - image: abelyankov/docker-example
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
