version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      # - database
      - redis
    ports:
      - "8000:3000"
    volumes:
      - .:/app
      # - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  # database:
  #   image: postgres:12.1
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:5.0.7

volumes:
  # gem_cache:
  db_data:
  node_modules: