apiVersion: v1
kind: Service
metadata:
  name: docker-example-service
spec:
  selector:
    app: docker-example-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 3000
  type: NodePort