apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: abelyankov/myapp:v1
        env:
        - name: DATABASE_HOST
          value: localhost
        - name: DATABASE_NAME
          value: myapp
        - name: DATABASE_USER
          value: myuser
        - name: DATABASE_PASSWORD
          value: passwd
        - name: DATABASE_PORT
          value: 57364
        - name: GREETING
          value: SALEM
        ports:
        - containerPort: 3000
        