apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: abelyankov/myapp:v1
        env:
        - name: DATABASE_HOST
          value: "postgresql+psycopg2://myuser:passwd@postgres:5432/app"
        - name: GREETING
          value: SALEM
        ports:
        - containerPort: 3000
        