apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: myapp
build:
  artifacts:
  - image: abelyankov/myapp
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
